version: '2.1'

services:
  nomad:
    image: multani/nomad
    build: .
    command: agent
    privileged: true
    network_mode: host
    environment:
      NOMAD_LOCAL_CONFIG: |
        datacenter = "dc1"
        region = "rg"

        data_dir = "/nomad/data/"

        server {
         enabled          = true
         bootstrap_expect = 1
        }

        advertise {
          http = "192.168.1.13:4646"
          rpc  = "192.168.1.13:4647"
          serf = "192.168.1.13:4648"
        }

        bind_addr = "0.0.0.0"
      NOMAD_DISABLE_PERM_MGMT: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
