version: '2.1'

services:
  nomad:
    image: multani/nomad
    build: .
    command: agent
    privileged: true
    network_mode: host
    environment:
      NOMAD_LOCAL_CONFIG: |
        datacenter = "dc1"
        region = "rg"
        data_dir = "/nomad/data/"

        server {
          enabled = false
        }
        client {
          enabled = true
          server_join {
            retry_join = ["192.168.1.13:4647"]
          }
        }
        advertise {
          http = "192.168.1.17:4646"
          rpc  = "192.168.1.17:4647"
          serf = "192.168.1.17:4648"
        }
        bind_addr = "0.0.0.0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw